config/routes.rb
Portfolio::Application.routes.draw do
  resources :faqs  
  constraints(:subdomain => /^blog$/) do
    match "/" => 'posts#index'
    resources :posts
  end

  match "/auth/:provider/callback" => "sessions#create"  
  match "/signout" => "sessions#destroy", :as => :signout  
  match "/admin" => "faqs#index"

  root :to => "home#index"
end

app/models/faq.rb
class Faq
  include MongoMapper::Document
  key :visible,       Boolean, :default => false
  key :question, String
  key :answer, String
  key :link, String
  key :tags, Array
  key :position, Integer
  timestamps!

  scope :visible, where(:visible => true)  
end

app/models/post.rb
class Post
  include MongoMapper::Document
  
  key :title, String
  key :content, String
  key :visible, Boolean, :default => false
  timestamps!
  scope :visible, where(:visible => true)  
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/user.rb
class User
  include MongoMapper::Document
  key :provider, String
  key :uid, String
  key :name, String
  key :admin, Boolean, :default => false
  
  #attr_protected :admin
  
  def self.create_with_omniauth(auth)  
    user = User.new(:name => auth["info"]["name"], 
                    :provider => auth["provider"],
                    :uid => auth["uid"]  
                   )
    user.save
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user  

  protected
  def must_be_admin
    unless current_user and current_user.admin?
      if current_user
        flash[:error] = "You must be an admin to do that."
        redirect_to root_url 
      else
        session[:redirect_target] = request.fullpath
        redirect_to "/auth/twitter" 
      end
    end
  end
  def must_be_signed_in
    !!@current_user
  end

  private  
  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end 

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_filter :must_be_admin
  # GET /faqs
  # GET /faqs.xml
  def index
    @faqs = Faq.sort(:position).all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @faqs }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.xml
  def show 
    @faq = Faq.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @faq }
    end
  end

  # GET /faqs/new
  # GET /faqs/new.xml
  def new
    @faq = Faq.new
    last = Faq.last(:order => :position)
    if last
      @faq.position = last.position + 1
    else
      @faq.position = 0
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @faq }
    end
  end

  # GET /faqs/1/edit
  def edit
    @faq = Faq.find(params[:id])
  end

  # POST /faqs
  # POST /faqs.xml
  def create
    @faq = Faq.new(params[:faq])

    respond_to do |format|
      if @faq.save
        format.html { redirect_to(faqs_url, :notice => 'Faq was successfully created.') }
        format.xml  { render :xml => @faq, :status => :created, :location => @faq }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @faq.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /faqs/1
  # PUT /faqs/1.xml
  def update
    @faq = Faq.find(params[:id])

    respond_to do |format|
      if @faq.update_attributes(params[:faq])
        format.html { redirect_to(faqs_url, :notice => 'Faq was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @faq.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.xml
  def destroy
    @faq = Faq.find(params[:id])
    @faq.destroy

    respond_to do |format|
      format.html { redirect_to(faqs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @about = Faq.find_by_question('about')
    @faqs = Faq.visible.sort(:position).all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :must_be_admin, :except => ['index', 'show']
  layout 'blog'
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.visible.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create  
    auth = request.env["omniauth.auth"]  
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)  
    session[:user_id] = user.id  
    do_redirect
  end 

  def destroy  
    session[:user_id] = nil  
    do_redirect
  end 

  def twitter
    session[:redirect_target] = request.referer unless session[:redirect_target]
    redirect_to :controller => :auth, :action => :twitter
  end

  private
  def do_redirect
    if session[:redirect_target]
      redirect_to session[:redirect_target]
      session[:redirect_target] = nil
    else
      redirect_to root_url 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def redcarpet 
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end 
  def markdown(text) 
    redcarpet.render(text).html_safe
  end
  def red(text)
    RedCloth.new(text).to_html.html_safe
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/faqs/_form.html.erb
<%= form_for(@faq) do |f| %>
  <% if @faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% @faq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question, :size => 55 %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :visible %><br />
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<div class="same_bg">
  <a href="#" id="toggle_all">Hide all</a>
  <ul id="qanda">
    <%= render :partial => 'home/faq', :collection => @faqs %>
    <%= link_to 'New Faq', new_faq_path %>
  </ul>
</div>

<script>
  $(".answer").show();
  $(".question").css("cursor", "n-resize");
</script>

app/views/faqs/new.html.erb
<h1>New faq</h1>

<%= render 'form' %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @faq.question %>
</p>

<p>
  <b>Answer:</b>
  <%= @faq.answer %>
</p>


<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>

app/views/home/_faq.html.erb
<div class="question">
  <% if current_user and current_user.admin %>
    <h2><%= link_to faq.question, edit_faq_path(faq) %></h2>
  <% else %>
    <h2><%= faq.question %></h2>
  <% end %>
</div>
<div class="answer">
  <%= markdown(faq.answer)%>
</div>

app/views/home/_footer.html.erb
<div id="ribbon_wrapper">
  <div class="ribbon">
    <a href="http://github.com/lashleigh/portfolio" rel="me">Fork me on GitHub</a>
  </div>
</div>

app/views/home/_header.html.erb
<h1>ashleigh baumgardner </h1>
<%= render 'home/static_network' %>
<%= image_tag('http://www.gravatar.com/avatar/3be78cd4d00d1de7591f489d02830dd5?s=100', :class => "gravatar") %>

app/views/home/_network.html.erb
<li>
<%= link_to image_tag(network.src), network.href, :title => network.src.split(".")[0] %> 
</li>

app/views/home/_static_network.html.erb
<ul id="networks" class='unstyled'>
  <% [['github',      "http://github.com/lashleigh"], 
    ['stackoverflow', "http://stackoverflow.com/users/337582/lashleigh"],
    ['facebook',      "http://www.facebook.com/#!/profile.php?id=25902647"],
    ['linkedin',      "http://linkedin.com/in/lashleigh"],
    ['twitter',       "http://twitter.com/lashleigh"],
    ['youtube',       "http://youtube.com/user/WasntThisAvailable"],
    ['flickr',        "http://www.flickr.com/photos/lashleigh"]].each do |name, url| %>
    <li> 
    <%= link_to image_tag('networks/'+name+'.png', :alt => name), href=url, :title => name %> 
    </li>
  <% end %>
</ul>

app/views/home/admin.html.erb
<% if !current_user %>
  <%= link_to "Sign in with Twitter", "/auth/twitter" %>  
<% end %>
<% if current_user and current_user.admin %>
  <%= link_to 'View and edit Faqs', faqs_path %>
  <%= link_to 'View and edit Networks', networks_path %>
<% end %>

app/views/home/index.html.erb
<% if @about %>
  <div id="about" class="hero-unit">
    <%= markdown(@about.answer) %>
  </div>
<% end %>
<div class="row">
  <div class="span1" id='up_arrow_span'>
  <%= image_tag 'up_arrow.png', :id => "arrow", :class=> 'arrow_up fast_transition' %>
</div>
  <div class="span9"  id='qanda'>
    <%= render :partial => 'faq', :collection => @faqs %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ashleigh</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <!-- Hello! You are inspecting my source code; that makes you such a geek. An -->
  <!-- awesome, awesome geek! Please don't hesitate to send me a message if you -->
  <!-- have any observations, questions or criticisms. Have a great day. -->
<%= yield %>

</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html><head>
    <title>Ashleigh</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
</head>
<body>
  <div id="page_wrap">
    <% flash.each do |name, msg| %>  
      <%= content_tag :div, msg, :id => "flash#{name}" %>  
    <% end %> 
    <div id="content_wrap">
      <%= render 'home/header' %>
      <div id="content">
        <%= yield %>
      </div>
      <%= render 'home/footer' %>
    </div>
  </div>
</body></html>

app/views/layouts/faqs.html.erb
<!DOCTYPE html><head>
    <title>Ashleigh</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
</head>
<body>
 <div id="page_wrap">
    <% flash.each do |name, msg| %>  
      <%= content_tag :div, msg, :id => "flash#{name}" %>  
    <% end %> 
    <div id="content_wrap">
      <div id="user_nav">  
        <% if current_user and current_user.admin %>  
          <%= link_to "Sign Out", signout_path %>  
          <%= link_to "Home", root_url %>
          <%= link_to "Blog", root_url(:host => "blog."+request.domain+request.port_string) %>
          <%= link_to "Faqs", faqs_path %>  
        <% end %>  
      </div>
      <div id="content">

        <%= yield %>
      </div>
    </div>
  </div>
</body></html>

app/views/layouts/home.html.erb
<!DOCTYPE html><head>
    <title>Ashleigh</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
</head>
<body>
  <div class='container'>
    <div id="flash_wrap">
      <% flash.each do |name, msg| %>  
        <%= content_tag :div, msg, :id => "flash#{name}" %>  
      <% end %> 
    </div>
    <div class="row">
      <span class="span12" id="name_header">
        <%= render 'home/header' %>
      </span>
    </div>
    <div class="row">
      <span class="span12" id='content'>
        <%= yield %>
      </span>
    </div>
    <%= render 'home/footer' %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :visible %><br />
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<h2><%=link_to post.title, post %></h2>

<div class="metadata">
  <span class="timestamp"><%= distance_of_time_in_words_to_now post.created_at %> ago</span>
  <% if current_user and current_user.admin? %>
    <span class="edit_links">
      <%= link_to image_tag("edit.png"), edit_post_path(post) %>
      <%= link_to image_tag("remove.png"),  post, :confirm => 'Are you sure?', :method => :delete %>
    </span>
  <% end %>
</div>

<div class="post_content">
  <%=red post.content%>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="blog_index">
<h1>Listing posts</h1>
<%= render :partial => 'post', :collection => @posts %>
</div>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>